name: Dump JP Update

on:
  schedule:
    # Run every Wednesday at 02:00, 05:00, 09:00, 12:00 UTC
    - cron: '0 2,5,9,12 * * 3'
    # Run everyday at 07:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force push update.'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  dump-jp-update:
    environment: "GitHub Action"
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Update remote branch references
        run: git fetch --all --tags

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.x'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Get Tools
        run: python getTools.py

      - name: Get APK & Dumper
        run: python getAndroidGameData.py --client jp
        
      - name: Run Dumper
        run: python getJPVersion.py

      - name: Save content temporary
        id: save_data
        shell: bash
        run: |
          TEMP_DIR="$RUNNER_TEMP/jp_update_data"
          mkdir -p "$TEMP_DIR"
          cp -r jp_data "$TEMP_DIR/"
          echo "temp_path=$TEMP_DIR/jp_data" >> $GITHUB_OUTPUT

      - name: Switch Branch
        run: git checkout jp-dump

      - name: Restore content
        shell: bash
        run: |
          TEMP_PATH="${{ steps.save_data.outputs.temp_path }}"
          cp -r "$TEMP_PATH" .

      - name: Check if config.json changed
        id: check_diff
        shell: bash
        run: |
          config_file="jp_data/config.json"
          changed_flag=false

          if git ls-tree -r origin/jp-dump --name-only | grep -Fxq "$config_file"; then
            if git diff --quiet origin/jp-dump -- "$config_file"; then
              echo "✅ The file is identical to the previous commit."
            else
              echo "⚠️ The file has been modified."
              changed_flag=true
            fi
          else
            echo "⚠️ The file does not exist. Add the file."
            changed_flag=true
          fi

          echo "changed=$changed_flag" >> $GITHUB_OUTPUT

      - name: Configure Git LFS
        if: >
          steps.check_diff.outputs.changed == 'true' || 
          github.event.inputs.force_update == 'true'
        shell: bash
        run: |
          git lfs install
          
          find ./jp_data -type f -size +50M -exec git lfs track {} \;

          if [ -f .gitattributes ]; then
            git add .gitattributes
            echo ".gitattributes has been updated"
          else
            echo "No files larger than 50MB were found."
          fi

      - name: Commit and Push Update
        if: >
          steps.check_diff.outputs.changed == 'true' || 
          github.event.inputs.force_update == 'true'
        shell: bash
        run: |
          game_version=$(jq -r '.GameVersion' jp_data/metadata.json)
          addressable_build=$(jq -r '.AddressableBuildVersion' jp_data/metadata.json)
          
          commit_msg="${game_version}_${addressable_build}"
          
          git add jp_data
          git commit -m "$commit_msg"
          git push origin jp-dump

      - name: Send update to Discord
        if: >
          steps.check_diff.outputs.changed == 'true' || 
          github.event.inputs.force_update == 'true'
        shell: bash
        run: |
          commit_hash=$(git rev-parse HEAD)
          commit_url="https://github.com/${GITHUB_REPOSITORY}/commit/${commit_hash}"
          prepath_raw_link="https://github.com/${GITHUB_REPOSITORY}/raw/${commit_hash}/jp_data/"
          treepath_link="https://github.com/${GITHUB_REPOSITORY}/tree/${commit_hash}/jp_data/"

          config_link="${prepath_raw_link}/config.json"
          dump_data_link="${prepath_raw_link}/cs/il2cpp.cs"
          fbs_v1_data_link="${prepath_raw_link}/BlueArchiveV1.fbs"
          fbs_v2_data_link="${prepath_raw_link}/BlueArchiveV2.fbs"
          dll_files="${treepath_link}/dll"
          
          game_version=$(jq -r '.GameVersion' jp_data/metadata.json)
          server_info_url=$(jq -r '.ServerInfoDataUrl' jp_data/metadata.json)
          server_info_version=$(jq -r '.ServerInfoVersion' jp_data/metadata.json)
          addressable_url=$(jq -r '.AddressableUrl' jp_data/metadata.json)
          addressable_version=$(jq -r '.AddressableVersion' jp_data/metadata.json)
          addressable_build_version=$(jq -r '.AddressableBuildVersion' jp_data/metadata.json)

          full_version="${game_version}_${addressable_build_version}"

          embed_description=$(cat <<EOF
          **Game Info**
          Game Version: ${game_version}
          Server Info Data Url: ${server_info_url}
          Server Info Data Version: ${server_info_version}
          Addressable Url: ${addressable_url}
          Addressable Version: ${addressable_version}
          Addressable Build Version: ${addressable_build_version}

          **Game Data**
          Config Data: [config.json](${config_link})
          Dump Data: [il2cpp.cs](${dump_data_link})
          FBS V1 (DummyDll Dump): [BlueArchiveV1.fbs](${fbs_v1_data_link})
          FBS V2 (Assembly Dump): [BlueArchiveV2.fbs](${fbs_v2_data_link})
          DummyDLL Files: [DummyDll](${dll_files})
          EOF
          )

          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          payload=$(jq -n \
            --arg title "JP Update (${full_version})" \
            --arg description "$embed_description" \
            --arg url "$commit_url" \
            --arg timestamp "$timestamp" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "url": $url,
                  "color": 255,
                  "timestamp": $timestamp
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
              -X POST \
              -d "$payload" \
              "${{ secrets.DISCORD_WEBHOOK_URL }}"
          echo "Discord notification sent."